local gameList = Instance.new("ScreenGui")
gameList.Name = "NAH" --"SB_GameList"
local frame = Instance.new("Frame", gameList)
frame.AnchorPoint = Vector2.new(0.5, 0.5)
frame.BackgroundColor3 = Color3.new()
frame.BackgroundTransparency = 0.6
frame.BorderSizePixel = 0
frame.Position = UDim2.new(0.5, 0, 0.5, 0)
frame.Size = UDim2.new(0, 500, 0, 300)
do
	local refresh = Instance.new("TextButton", frame)
	refresh.Name = "Refresh"
	refresh.Active = true
	refresh.BackgroundColor3 = Color3.new()
	refresh.BackgroundTransparency = 0.75
	refresh.BorderColor3 = Color3.new(1, 1, 1)
	refresh.Font = "Legacy"
	refresh.FontSize = "Size8"
	refresh.Position = UDim2.new(0.01, 0, 0, 5)
	refresh.Size = UDim2.new(0, 58, 0, 20)
	refresh.Text = "Refresh"
	refresh.TextColor3 = Color3.new(1, 1, 1)
	refresh.TextStrokeColor3 = Color3.new()
	refresh.TextStrokeTransparency = 1
	local exit = Instance.new("TextButton", frame)
	exit.Name = "Exit"
	exit.AnchorPoint = Vector2.new(1, 0)
	exit.BackgroundColor3 = Color3.new()
	exit.BackgroundTransparency = 0.75
	exit.BorderColor3 = Color3.new(1, 1, 1)
	exit.Font = "Legacy"
	exit.FontSize = "Size8"
	exit.Position = UDim2.new(0.99, 0, 0, 5)
	exit.Size = UDim2.new(0, 30, 0, 20)
	exit.Text = "Exit"
	exit.TextColor3 = Color3.new(1, 0, 0)
	exit.TextStrokeColor3 = Color3.new()
	exit.TextStrokeTransparency = 1
	local scroll = Instance.new("ScrollingFrame", frame)
	scroll.AnchorPoint = Vector2.new(0.5, 1)
	scroll.BackgroundColor3 = Color3.new()
	scroll.BackgroundTransparency = 0.9
	scroll.BorderSizePixel = 0
	scroll.CanvasSize = UDim2.new(0, 490, 0, 60)
	scroll.Position = UDim2.new(0.5, 0, 1, 0)
	scroll.ScrollBarThickness = 6
	scroll.Size = UDim2.new(0.98, 0, 1, -30)
	do
		local UIList = Instance.new("UIListLayout", scroll)
		UIList.Padding = UDim.new(0, 5)
		local default = Instance.new("Frame", scroll)
		default.Name = "Default"
		default.BackgroundColor3 = Color3.new()
		default.BackgroundTransparency = 0.6
		default.BorderColor3 = Color3.new()
		default.BorderSizePixel = 0
		default.Position = UDim2.new()
		default.Size = UDim2.new(1, -12, 0, 100)
		do
			local expand = Instance.new("TextButton", default)
			expand.Name = "Expand"
			expand.BackgroundColor3 = Color3.new()
			expand.BackgroundTransparency = 0.5
			expand.BorderSizePixel = 0
			expand.Size = UDim2.new(1, 0, 0, 25)
			expand.Font = "SourceSans"
			expand.FontSize = "Size14"
			expand.Text = "  [CLICK TO EXPAND] ServerID: " -- Editable
			expand.TextColor3 = Color3.fromRGB(225, 225, 225)
			expand.TextStrokeColor3 = Color3.new()
			expand.TextStrokeTransparency = 0
			expand.TextXAlignment = "Left"
			expand.ZIndex = 5
			local body = Instance.new("TextLabel", default)
			body.Name = "Body"
			body.AnchorPoint = Vector2.new(0.5, 1)
			body.BackgroundTransparency = 1
			body.BorderSizePixel = 0
			body.Font = "SourceSans"
			body.FontSize = "Size14"
			body.Position = UDim2.new(0.5, 0, 1, -25)
			body.Size = UDim2.new(1, 0, 0, 50)
			body.Text = "FPS: 59.97 | PlayerCount: 1\nJhonXD2006,DrawingJhon,Artem1237894" -- Editable
			body.TextColor3 = Color3.fromRGB(240, 240, 240)
			body.TextStrokeTransparency = 1
			body.TextYAlignment = "Top"
			local join = Instance.new("TextButton", default)
			join.AnchorPoint = Vector2.new(0.5, 1)
			join.Name = "Join"
			join.BackgroundTransparency = 1
			join.BorderSizePixel = 0
			join.Font = "SourceSans"
			join.FontSize = "Size14"
			join.Position = UDim2.new(0.5, 0, 1, 0)
			join.Size = UDim2.new(1, 0, 0, 25)
			join.Text = "Join Server"
			join.TextColor3 = Color3.fromRGB(5, 168, 255)
			join.TextStrokeTransparency = 1
		end
	end
	local title = Instance.new("TextLabel", frame)
	title.AnchorPoint = Vector2.new(0.5, 0)
	title.Name = "Title"
	title.BackgroundTransparency = 1
	title.BorderSizePixel = 0
	title.Font = "SourceSans"
	title.FontSize = "Size18"
	title.TextSize = 16
	title.Position = UDim2.new(0.5, 0, 0, 0)
	title.Size = UDim2.new(0, 200, 0, 30)
	title.Text = "#Aesthetics (Gamelist)"
	title.TextColor3 = Color3.new(1, 1, 1)
	title.TextStrokeTransparency = 1
end

gameList.Parent = owner.PlayerGui