local screen = Instance.new("ScreenGui", owner.PlayerGui)
screen.Name = "Bar"
local frame = Instance.new("Frame", screen)
frame.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
frame.BackgroundTransparency = 0.8
frame.BorderSizePixel = 0
--frame.Position = UDim2.new(0, 0, 0.35, 0)
frame.Position = UDim2.new(0, 0, 0.35, 55)
frame.Size = UDim2.new(1, 0, 0, 50)
frame.Visible = true
local text = Instance.new("TextBox", frame)
text.Font = "Arial"
text.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
text.BackgroundTransparency = 0.5
text.FontSize = "Size24"
text.Position = UDim2.new(0, 0, 0, 4)
text.Size = UDim2.new(1, 0, 1, -8)
text.TextColor3 = Color3.fromRGB(255, 255, 255)
text.TextStrokeColor3 = Color3.fromRGB(86, 86, 86)
text.TextStrokeTransparency = 0.7
text.TextWrapped = true
text.Text = "Hola :D"