local part = Instance.new("Part",workspace)
part.Name = "Bruh"
part.Position = Vector3.new(0, 3, 0)
part.Size = Vector3.new(2, 2, 2)
part.Anchored = true
part.TopSurface = Enum.SurfaceType.Smooth
part.BottomSurface = Enum.SurfaceType.Smooth
local bg = Instance.new("BillboardGui",part)
local tl = Instance.new("TextLabel",bg)
bg.AlwaysOnTop = false
bg.Enabled = true
bg.Size = UDim2.new(4, 1, 1, 0)
bg.SizeOffset = Vector2.new(0, 2)
bg.Active = false
tl.TextColor3 = Color3.fromRGB(255, 255, 255)
tl.TextWrapped = true
tl.TextScaled = true
tl.Size = UDim2.new(1, 0, 1, 0)
tl.Position = UDim2.new(0, 0, 0, 0)
tl.BackgroundTransparency = 1
tl.Font = Enum.Font.Cartoon
tl.TextTransparency = 0.5